title: ElixirConf EU Virtual
description: > # this means to ignore newlines until "baseurl:"
  ElixirConf EU Virtual 2020
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://virtual.elixirconf.eu" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

logo: "./assets/images/icon-large.png"

social: 
  name: ElixirConf EU Virtual
  link: "https://twitter.com/elixirconfeu"

# google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: [index.html]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/elixirconfeu
    username: elixirconfeu
    card: image

# Build settings
markdown: kramdown
permalink: pretty

collections:
  speakers:
    output: true
    sort_by: relevance
  keynotes:
    output: true
    sort_by: relevance
  trainers:
    output: true
    sort_by: relevance
  trainings:
    output: true
    sort_by: relevance
  talks:
    output: true
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "speakers"
    values:
      layout: "speaker"
  - scope:
      path: ""
      type: "trainers"
    values:
      layout: "speaker"
  - scope:
      path: ""
      type: "trainings"
    values:
      layout: "training"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Online, from the comforts of your own home
map-text-location: Anywhere in the world
map-lat: 52.2335221
map-lng: 20.9836819



