---
- from: 15 June, 13:00 CEST
  to: 16 June, 17:00 CEST
  type: ''
  training_1: Riak Introductory Training
  training_1_url: riak-introductory
  training_1_instructor: ''
  training_1_instructor_2: ''
  training_2: ''
  training_2_url: ''
  training_2_instructor: ''
- from: 17 June, 10AM CEST
  to: 17 June, 6PM CEST
  type: ''
  training_1: Elixir with Kubernetes
  training_1_url: elixir-with-kubernetes
  training_1_instructor: Bryan Hunt
  training_1_instructor_2: ''
  training_2: ''
  training_2_url: ''
  training_2_instructor: ''
- from: 17 June, 10AM CEST
  to: 17 June, 2PM CEST
  type: ''
  training_1: Distributed Live Tracing
  training_1_url: distributed-live-tracing
  training_1_instructor: Gabor Olah
  training_1_instructor_2: ''
  training_2: ''
  training_2_url: ''
  training_2_instructor: ''
- from: 8 June - 10 June, 9AM
  to: 5PM ART
  type: ''
  training_1: Elixir para Principiantes
  training_1_url: elixir-para-principiantes
  training_1_instructor: Manuel Rubio
  training_1_instructor_2: ''
  training_2: ''
  training_2_url: ''
  training_2_instructor: ''
- from: 15 June - 17 June, 9AM
  to: 6PM CEST
  type: training
  training_1: Elixir Programming for Beginners
  training_1_url: elixir-programming-for-beginners
  training_1_instructor: Mikael Muszyński
  training_1_instructor_2: ''
  training_2: ''
  training_2_url: ''
  training_2_instructor: ''
- from: 17 June, 3PM
  to: 7PM CEST
  type: training
  training_1: Programming Phoenix with LiveView
  training_1_url: programming-phoenix-with-liveview
  training_1_instructor: Bruce Tate
  training_1_instructor_2: ''
  training_2: ''
  training_2_url: ''
  training_2_instructor: ''
