---
- from: 9.00 AM day 1
  to: 5.00 PM day 1
  type: training
  training_1: Debugging a running system
  training_1_url: debugging-a-running-system
  training_1_instructor: Ben Marx
  training_1_instructor_2: Justin Schneck
  training_2: ''
  training_2_url: ''
  training_2_instructor: ''
