---
- from: 17 June, 3PM
  to: 7PM CEST
  type: training
  training_1: Programming Phoenix with LiveView
  training_1_url: programming-phoenix-with-liveview
  training_1_instructor: Bruce Tate
  training_1_instructor_2: ''
  training_2: ''
  training_2_url: ''
  training_2_instructor: ''
