---
label: Training
hide_body: false
display_field: speaker
fields:
- type: text
  name: speaker
  label: speaker
- type: text
  name: trainer
  label: trainer
- name: trainer-name
  type: text
  config:
    required: false
  label: trainer-name
- type: text
  name: event_date
  label: event_date
- type: text
  name: venue
  label: venue
- type: text
  name: summary
  label: summary
- type: textarea
  name: description
  label: description
- type: text
  name: experience
  label: experience
- type: text
  name: from
  label: from
- type: text
  name: to
  label: to
- type: text
  name: type
  label: type
- name: pic_url
  type: file
  config:
    maxSize: 2
  label: pic_url
- name: draft
  type: boolean
  label: draft
pages:
- _trainings/distributed-live-tracing.md
- _trainings/distributed-programming.md
- _trainings/elixir-with-kubernetes.md
- _trainings/riak-intermediate.md
- _trainings/riak-introductory.md
- _trainings/sfdfgdfdgfgd.yml.md
